ToOrder.Web/Areas/Admin/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToOrder.Core.Services.Interfaces;
using PagedList;
using ToOrder.Core.Entities;
using ToOrder.Web.App_Start;
using System.Globalization;
using System.IO;
using ToOrder.Web.Controllers;

namespace ToOrder.Web.Areas.Admin.Controllers
{
    public class RestaurantController : BaseController
    {
        IRestaurantService _restaurantService;
        public RestaurantController(IRestaurantService restaurantService)
        {
            _restaurantService = restaurantService;
        }


        


        // GET: Admin/Restaurant
        public ActionResult Index(int? page)
        {
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = ToOrderConfigs.DefaultPageSize;

            int total;
            var restaurants = _restaurantService.GetAll(pageNumber, pageSize, out total);

            //using StaticPagedList for better performance
            return View(new StaticPagedList<Restaurant>(restaurants, pageNumber, pageSize, total));
        }



        public ActionResult Search(string restaurant, string cuisine, int? page)
        {
            ViewBag.resturantName = restaurant;
            ViewBag.cuisine = cuisine;

            int pageNumber = page != null ? page.Value : 1;
            int pageSize = ToOrderConfigs.DefaultPageSize;

            int total;


            var restaurants = _restaurantService.GetAll(r => restaurant == null || r.Name.IndexOf(restaurant, StringComparison.InvariantCultureIgnoreCase) >= 0, pageNumber, pageSize, out total);
            return View("Index", new StaticPagedList<Restaurant>(restaurants, pageNumber, pageSize, total));
        }

        // GET: Admin/Restaurant/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Restaurant/Create
        public ActionResult Create()
        {
            var restaurant = new Restaurant();

            return View(restaurant);
        }

        // POST: Admin/Restaurant/Create
        [HttpPost]
        public ActionResult Create(Restaurant restaurant, HttpPostedFileBase uploadFile)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string folderPath = @"\Pictures\Restaurant";
                    string folderPathOnServer = Server.MapPath(folderPath);
                    if (!Directory.Exists(folderPathOnServer))
                    {
                        Directory.CreateDirectory(folderPathOnServer);
                    }
                    if (uploadFile != null)
                    {
                        if (uploadFile.ContentLength <= 2000000)
                        {
                            var allowedExtensions = new[] { ".jpg", ".png" };
                            var filename = Path.GetFileName(uploadFile.FileName);
                            var ext = Path.GetExtension(uploadFile.FileName);

                            if (allowedExtensions.Contains(ext))
                            {
                                restaurant.PictureFileName = filename;
                                restaurant.CreationDate = System.DateTime.Now;
                                _restaurantService.AddNew(restaurant);

                                int resID = restaurant.Id;
                                string myPicture = resID + "_" + filename;
                                var path = Path.Combine(folderPathOnServer, myPicture);
                                uploadFile.SaveAs(path);

                                return RedirectToAction("Index");
                            }
                            else
                            {
                                ModelState.AddModelError("", "Image Extension is not Valid");
                                return View(restaurant);
                            }
                        }
                        else
                        {
                            ModelState.AddModelError("", "Please Select Proper Image ");
                            return View(restaurant);
                        }
                    }
                    else
                    {
                        restaurant.CreationDate = System.DateTime.Now;
                        _restaurantService.AddNew(restaurant);
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    return   View(restaurant);
                }
            }
            catch (Exception ex)
            {
                this.Response.StatusCode = 400;
                if (ex is InvalidOperationException)
                    ModelState.AddModelError("", "Please correct following errors:");
                else
                    ModelState.AddModelError("", ex.Message);
                return RedirectToAction("Create");
            }
        }

        // GET: Admin/Restaurant/Edit/5
        public ActionResult Edit(int id)
        {
            var restaurant = _restaurantService.GetById(id);
            return View(restaurant);
        }

        // POST: Admin/Restaurant/Edit/5
        [HttpPost]
        public ActionResult Edit(Restaurant restaurant, HttpPostedFileBase uploadFile)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string folderPath = @"\Pictures\Restaurant";
                    string folderPathOnServer = Server.MapPath(folderPath);
                    if (!Directory.Exists(folderPathOnServer))
                    {
                        Directory.CreateDirectory(folderPathOnServer);
                    }
                    if (uploadFile != null)
                    {
                        if (uploadFile.ContentLength <= 2000000)
                        {
                            var allowedExtensions = new[] { ".jpg", ".png" };
                            var filename = Path.GetFileName(uploadFile.FileName);
                            var ext = Path.GetExtension(uploadFile.FileName);

                            if (allowedExtensions.Contains(ext))
                            {
                                restaurant.PictureFileName = filename;
                                _restaurantService.Update(restaurant);

                                int resID = restaurant.Id;
                                string myPicture = resID + "_" + filename;
                                var path = Path.Combine(folderPathOnServer, myPicture);
                                uploadFile.SaveAs(path);

                                return RedirectToAction("Index");
                            }
                            else
                            {
                                ModelState.AddModelError("", "Image Extension is not Valid");
                                return View(restaurant);
                            }
                        }
                        else
                        {
                            ModelState.AddModelError("", "Please Select Proper Image ");
                            return View(restaurant);
                        }
                    }
                    else
                    {
                        _restaurantService.Update(restaurant);
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    return RedirectToAction("Edit", new { restaurantId = restaurant.Id });
                }
            }
            catch (Exception ex)
            {
                this.Response.StatusCode = 400;
                if (ex is InvalidOperationException)
                    ModelState.AddModelError("", "Please correct following errors:");
                else
                    ModelState.AddModelError("", ex.Message);
                return RedirectToAction("Edit", new { restaurantId = restaurant.Id });
            }
        }

        // GET: Admin/Restaurant/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/Restaurant/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Dashboard()
        {
            return View();
        }
    }
}

ToOrder.Web/Areas/RestaurantAdmin/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToOrder.Core.Entities;
using ToOrder.Core.Services.Interfaces;
using ToOrder.Web.Controllers;


namespace ToOrder.Web.Areas.RestaurantAdmin.Controllers
{
    [Authorize(Roles = "Admin,RestaurantOwner, RestaurantUser")]
    public class RestaurantController : BaseController
    {
        IRestaurantService _restaurantService;
        IUserService _userServce;

        public RestaurantController(IRestaurantService restaurantService, IUserService userService)
        {
            _restaurantService = restaurantService;
            _userServce = userService;
        }


        public ActionResult SelectRestaurant(int id)
        {
            Session["restaurantId"] = id;
            var restaurantName = _restaurantService.GetById(id).Name;
            Session["restaurantName"] = restaurantName;
            return RedirectToAction("Index");
        }


        // GET: RestaurantAdmin/Restaurant
        public ActionResult Index()
        {
            int id = this.CurrentRestaurantId(); ;
            var restaurant = _restaurantService.GetById(id);

            return RedirectToAction("Dashboard");
        }

        [Authorize(Roles = "RestaurantOwner")]

        public ActionResult MyRestaurants()
        {
                var user = GetAuthenticatedUser();

                if (user == null)
                    return Content("Not authorized!");

                var restaurants = _restaurantService.GetAll(r => r.RestaurantUsers.Where(u => u.UserId == user.Id).Any());

                if (restaurants.Count() > 1)
                    return View(restaurants);
                else if (restaurants.Count() == 1)
                {
                    Session["restaurantId"] = restaurants.First().Id;
                    return Content("Show Restaurant Individual Page");
                }
                else
                {
                    return Content("No restaurants under your email id");
                }

            }


        public ActionResult Edit()
        {
            var restaurantId = this.CurrentRestaurantId();

            if (restaurantId == 0)
                return RedirectToAction("MyRestaurants");

            var restaurant = _restaurantService.GetById(restaurantId);

            return View(restaurant);
        }


        [HttpPost]
        public ActionResult Edit(Restaurant restaurant, HttpPostedFileBase uploadFile)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    string folderPath = @"\Pictures\Restaurant";
                    string folderPathOnServer = Server.MapPath(folderPath);
                    if (!Directory.Exists(folderPathOnServer))
                    {
                        Directory.CreateDirectory(folderPathOnServer);
                    }
                    if (uploadFile != null)
                    {
                        if (uploadFile.ContentLength <= 2000000)
                        {
                            var allowedExtensions = new[] { ".jpg", ".png", ".gif", ".jpeg" };
                            var filename = Path.GetFileName(uploadFile.FileName);
                            var ext = Path.GetExtension(uploadFile.FileName);

                            if (allowedExtensions.Contains(ext))
                            {
                                restaurant.PictureFileName = filename;
                                _restaurantService.Update(restaurant);

                                int resID = restaurant.Id;
                                string myPicture = resID + "_" + filename;
                                var path = Path.Combine(folderPathOnServer, myPicture);
                                uploadFile.SaveAs(path);

                                return RedirectToAction("Edit");
                            }
                            else
                            {
                                ModelState.AddModelError("", "Image Extension is not Valid");
                                return View(restaurant);
                            }
                        }
                        else
                        {
                            ModelState.AddModelError("", "Please Select Proper Image ");
                            return View(restaurant);
                        }
                    }
                    else
                    {
                        _restaurantService.Update(restaurant);
                        return RedirectToAction("Edit");
                    }
                }
                else
                {
                    return RedirectToAction("Edit");
                }
            }
            catch (Exception ex)
            {
                this.Response.StatusCode = 400;
                if (ex is InvalidOperationException)
                    ModelState.AddModelError("", "Please correct following errors:");
                else
                    ModelState.AddModelError("", ex.Message);
                return RedirectToAction("Edit");
            }
        }

        public ActionResult Dashboard()
        {
            var restaurantId = this.CurrentRestaurantId();
            if (restaurantId == 0)
                return RedirectToAction("MyRestaurants", "Restaurant");
            return View();
        }
    }
}

ToOrder.Web/Controllers/MenuCardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToOrder.Core.Entities;
using ToOrder.Core.Services.Interfaces;
using ToOrder.Data;
using ToOrder.Web.ViewModels;

namespace ToOrder.Web.Controllers
{
    public class MenuCardController : Controller
    {
        IMenuCardService _menucardService;
        IMenuItemService _menuitemService;
        ICategoryService _categoryService;
        IRestaurantService _restaurantService;

        public MenuCardController(IMenuCardService menucardService, IMenuItemService menuitemService, ICategoryService categoryService, IRestaurantService restaurantService)
        {
            _menucardService = menucardService;
            _menuitemService = menuitemService;
            _categoryService = categoryService;
            _restaurantService = restaurantService;
        }
        // GET: MenuCard
        public ActionResult Index(int restaurantId)
        {
            var items = _menuitemService.GetAll(i => i.MenuCard.IsDefault && i.MenuCard.RestaurantId == restaurantId).OrderBy(i => i.Category.Name);
            ViewBag.restaurantId = restaurantId;
            var restaurant = _restaurantService.GetById(restaurantId);
            HttpCookie cookie = new HttpCookie("userInfo");
            if (cookie != null)
            {
                cookie.Expires = DateTime.Now.AddYears(1);
                cookie.Values.Add("Locality", restaurant.Address.Locality);
                cookie.Values.Add("lattitude", restaurant.Latitude.ToString());
                cookie.Values.Add("longitude", restaurant.Longitude.ToString());
            }// update cookie value
            else
            {
                cookie = new HttpCookie("userInfo");
                cookie.Values.Add("Locality", restaurant.Address.Locality);
                cookie.Values.Add("lattitude", restaurant.Latitude.ToString());
                cookie.Values.Add("longitude", restaurant.Longitude.ToString());
                cookie.Expires = DateTime.Now.AddYears(1);
            }
            Response.Cookies.Add(cookie);
            return View(items.ToList());
        }


        public ActionResult SearchMenuItem(string keywords, int restaurantId)
        {
            var items = _menuitemService.GetAll(r => (keywords == null || r.Name.Contains(keywords)) && r.MenuCard.IsDefault && r.MenuCard.RestaurantId == restaurantId).OrderBy(i => i.Category.Name);
            ViewBag.restaurantId = restaurantId;

            return View("Index", items.ToList());
        }
    }
}

ToOrder.Web/Views/Restaurant/GoogleMapPartial.cshtml
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="section-title">
            <span class="glyphicon glyphicon-globe"></span>  <label>Location Map</label>
        </div>
        <div id="map" style="width:100%;height:300px;"></div>
    </div>
}

<script>
    var myCenter;
    var mapOptions;
    var map;
    var marker;
    var infowindow;
    function myMap() {

        var geocoder = new google.maps.Geocoder();
        var address = document.getElementById('Address_Locality').value;

        var latitude = document.getElementById('Latitude').value;
        var lat = latitude.toString().replace(',', '.');

        var longitude = document.getElementById('Longitude').value;
        var lon = longitude.toString().replace(',', '.');

        var zoomVal = parseInt(document.getElementById('Zoom').value);
        if (zoomVal == 0) {
            zoomVal = 13;
        }

        if (lat == 0 || lon == 0) {
            geocoder.geocode({ 'address': address }, function (results, status) {
                if (status == 'OK') {
                    myCenter = new google.maps.LatLng(results[0].geometry.location.lat(), results[0].geometry.location.lng());
                    mapOptions = { center: myCenter, zoom: zoomVal }

                    document.getElementById('Latitude').value = results[0].geometry.location.lat();
                    document.getElementById('Longitude').value = results[0].geometry.location.lng();
                    
                    MapInfo();
                }
                else {
                    alert('Geocode was not successful for the following reason: ' + status);
                }
            });
        }
        else {
            myCenter = new google.maps.LatLng(lat, lon);
            mapOptions = { center: myCenter, zoom: zoomVal };

            MapInfo();
        }
    }

    function MapInfo() {
        var mapCanvas = document.getElementById("map");
        map = new google.maps.Map(mapCanvas, mapOptions);
        marker = new google.maps.Marker({ position: myCenter, draggable: false });
        marker.setMap(map);

        infowindow = new google.maps.InfoWindow({
            content: "<b>Latitude:  </b>" + myCenter.lat() + "<br/> <b>Longitude:  </b>" + myCenter.lng()
        });
        infowindow.open(map, marker);
    }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDZkNTEJ2QUqe6PyeOVOBwjUuKzg7YeE2A&callback=myMap"></script>

ToOrder.Web/Views/Restaurant/GoogleMapRestaurants.cshtml
@model IEnumerable<ToOrder.Core.Entities.Restaurant>
@{
    ViewBag.Title = "GoogleMapRestaurants";
}

<p id="demo"></p>
<div id="map" style="width:100%;height:500px"></div>

<script>
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition,showError);
    }

    function myMap(lat,long) {
        var zoomLevel=2;
        var x = document.getElementById("demo");
        var image1 = {
            url: "@Url.Content("~/Content/Images/marker.png")",
            scaledSize: new google.maps.Size(27, 22),
        };
        var infoWindowArray = new Array();
        var mapCanvas = document.getElementById("map");
        if(lat==0 || lat===undefined )
        {
            center = new google.maps.LatLng(20.593684, 78.96288000000004);

        }
        else{

            center = new google.maps.LatLng(lat, long);
            zoomLevel=20;

        }

        var mapOptions = {
            center: center,
            zoom: zoomLevel,
            scrollwheel: false
        };
        var map = new google.maps.Map(mapCanvas, mapOptions);

        @foreach(var item in Model)
                {
                <text>
        if(@item.Latitude!=0)
        {
            var latlng = new google.maps.LatLng('@item.Latitude', '@item.Longitude');
            var infowindow = new google.maps.InfoWindow();
            var contentStringCal = '<div class="infoWindow"><strong><b>@item.Name</b></strong></div>';
            marker = new google.maps.Marker({ position: latlng, draggable: false,icon:image1,title:"Click here for details"});
            marker.setMap(map);

            bindInfoWindow(marker, map, infowindow, contentStringCal);

            marker.addListener('click', function() {
                location.href = "@Url.Action("Index", "MenuCard", new { restaurantId = item.Id })";
            });

            map.addListener('click',function(){
                map.set('scrollwheel',true);
            });
            map.addListener('mouseout', function() {
                map.set('scrollwheel',false);
            });

        }
        else{
            var geocoder = new google.maps.Geocoder();
            setTimeout(function(){ geocoder.geocode({ 'address': '@item.Address.Locality' }, function (results, status) {
                if (status == 'OK') {
                    var latlng =  new google.maps.LatLng(results[0].geometry.location.lat(), results[0].geometry.location.lng());
                    var infowindow = new google.maps.InfoWindow();
                    var contentStringCal = '<div class="infoWindow"><strong><b>@item.Name</b></strong></div>';
                    marker = new google.maps.Marker({ position: latlng, draggable: false,icon:image1,title:"Click here for details"});
                    marker.setMap(map);
                    bindInfoWindow(marker, map, infowindow, contentStringCal);
                    marker.addListener('click', function() {
                        location.href = "@Url.Action("Index", "MenuCard", new { restaurantId = item.Id })";
                    });

                    map.addListener('click',function(){
                        map.set('scrollwheel',true);
                    });
                    map.addListener('mouseout', function() {
                        map.set('scrollwheel',false);
                    });

                }
                else
                    if(status == "OVER_QUERY_LIMIT")
                    {
                        setTimeout(200);
                    }
                    else {
                        alert('Geocode was not successful for the following reason: ' + status);
                    }

            })},200);

        }
        </text>
        }


    }
    function bindInfoWindow(marker, map, infowindow, html) {
        marker.addListener('mouseover', function() {
            infowindow.setContent(html);
            infowindow.open(map, this);
        });

        marker.addListener('mouseout', function() {
            infowindow.close(map,this);
        });
    }

    function showPosition(position) {
        myMap(position.coords.latitude,position.coords.longitude);

    }
    function showError() {

        var address='';
        var lattitude='';
        var longitude='';

        @{
            if(Request!=null && Request.Cookies!=null && Request.Cookies.Get("userInfo")!=null)
            {
                <text>

        address='@Request.Cookies["userInfo"]["Locality"]';
        lattitude=@Request.Cookies["userInfo"]["lattitude"];
        longitude=@Request.Cookies["userInfo"]["longitude"];
        </text>
            }
        }
        if(address=='' && lattitude=='' && longitude=='')
        {
            myMap(0.0,0.0);
        }
        else{

            if(lattitude!='' && longitude!=''){
                myMap(lattitude, longitude);
            }
            else{
                var geocoder = new google.maps.Geocoder();
                geocoder.geocode({ 'address': address }, function (results, status) {
                    if (status === google.maps.GeocoderStatus.OK) {
                        myMap(results[0].geometry.location.lat(), results[0].geometry.location.lng());
                    }
                    else {
                        myMap(0.0,0.0);
                    }
                });

            }
        }

    }

</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDZkNTEJ2QUqe6PyeOVOBwjUuKzg7YeE2A&callback=myMap"></script>

ToOrder.Web/Views/Restaurant/RestaurantDetails.cshtml
@model ToOrder.Core.Entities.Restaurant

@{
    Layout = null;
}

<div class="container">

    @using (Ajax.BeginForm(new AjaxOptions { OnSuccess = "handleSuccessRestaurant", OnFailure = "handleError" }))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.Address.Locality)
        @Html.HiddenFor(model => model.Latitude)
        @Html.HiddenFor(model => model.Longitude)
        @Html.HiddenFor(model => model.Zoom)

            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-12">
                        <div class="row">
                            <h3>@Model.Name</h3><hr />
                        </div>
                        <div class="row">
                            <div class=" col-md-6">
                                <i class="glyphicon glyphicon-map-marker"></i><label>@Resources.Address</label><hr style="margin-top:0px" />
                                <label>@Resources.Street</label>:   <span>@Model.Address.Street</span><br />
                                <label>@Resources.Locality</label>:   <span id="address_Locality">@Model.Address.Locality</span><br />
                                <label>@Resources.Region</label>:   <span>@Model.Address.Region</span><br />
                                <label>@Resources.Country</label>:   <span>@Model.Address.Country</span>
                            </div>
                            <div class=" col-md-6">
                                <i class="glyphicon glyphicon-map-marker"></i><label>@Resources.Contact</label><hr style="margin-top:0px" />
                                <label>@Resources.Email</label>:   <span>@Model.Contact.Email</span><br />
                                <label>@Resources.Website</label>:   <span>@Model.Contact.Website</span><br />
                                <label>@Resources.FaxNumber</label>:   <span>@Model.Contact.FaxNumber</span><br />
                                <label>@Resources.Telephone</label>:   <span>@Model.Contact.Telephone</span>
                            </div>
                        </div><hr />

                        <div class="row">
                            @{Html.RenderPartial("GoogleMapPartial", Model);}
                        </div>
                    </div>
                </div>
            </div>
    }
</div>

ToOrder.Web/Views/Restaurant/RestaurantList.cshtml
@model IEnumerable<ToOrder.Core.Entities.Restaurant>


@if (Model == null || Model.Count() < 1)
{
    <div class="text-center ">
        <label class="text-danger">@Resources.NoRestaurantsfound</label> <br />
        <span>@Resources.CheckPopulerRestaurant:</span>
    </div>
    <div style="background-color:white; margin:20px;">
        @{Html.RenderAction("SponsoredRestaurants", "Restaurant");}
    </div>
}
else
{

    foreach (var item in Model)
    {

        <div class="col-md-6 col-lg-5">
            <a style="text-decoration: none;" href="@Url.Action("Index", "MenuCard", new { restaurantId = item.Id })">
                <div class="boxShadow left-container">
                    <div class="restaurantpicture left">
                        <img src="@Url.Content( "~/Pictures/Restaurant/" + item.Id + "_" + item.PictureFileName)" class="img-responsive" style="height:100%; width:100%; " onerror="this.onerror = null; this.src = '/Images/restaurant-default.png';">
                    </div>
                    <div class="restaurantDetails">
                        <h4>@item.Name </h4>

                        <div class="cuisineList">
                            @foreach (var cuisine in item.Cuisine)
                            {
                                @(cuisine.Cuisine.Name + " ")
                            }
                        </div>
                        <hr />

                        @for (int i = 1; i <= 4; i++)
                        {
                            if (i <= item.Budget)
                            {
                                <span class="currency currency-active glyphicon glyphicon-usd small"></span>
                            }
                            else
                            {
                                <span class="currency glyphicon glyphicon-usd small"></span>
                            }
                        }

                        @{
                            var count=0;
                            var temp=0;
                            var average=0;
                            foreach(var rating in item.Rating)
                            {
                            temp+=rating.Ratings;
                                count++;

                            }
                            if (count > 0) { 
                            average = temp / count;
                            }
                      }
                        <span class="pull-right">
                            @average <span class="glyphicon glyphicon-star stars"></span>
                        </span>
                    </div>


                </div>
            </a>
        </div>
    }
}

ToOrder.Web/Views/Restaurant/SponsoredRestaurants.cshtml
@model IEnumerable<ToOrder.Core.Entities.Restaurant>

<div class="sponsoredRestaurants">
    <h2>@Resources.PopularRestaurants</h2>



    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-3 col-lg-3">
                <div class="card">
                    <a style="text-decoration: none;" href="@Url.Action("Index", "MenuCard", new { restaurantId = item.Id })">
                        <div class="restaurantpicture">
                            <img src="@Url.Content( "~/Pictures/Restaurant/" + item.Id + "_" + item.PictureFileName)" class="" style="height:100%; width:100%; " onerror="this.onerror = null; this.src = '/Images/restaurant-default.png';">
                        </div>
                        <span>@item.Name</span>
                    </a>
                </div>
            </div>


        }
    </div>
</div>