ToOrder.Web/Areas/Admin/Controllers/OrderController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToOrder.Core.Entities;
using ToOrder.Core.Services.Interfaces;
using ToOrder.Web.App_Start;
using ToOrder.Web.Controllers;

namespace ToOrder.Web.Areas.Admin.Controllers
{
    public class OrderController : BaseController
    {
        IOrderService _orderService;
        IRestaurantService _restaurantService;

        public OrderController(IOrderService orderService, IRestaurantService restaurantService)
        {
            _orderService = orderService;
            _restaurantService = restaurantService;
        }

        // GET: Admin/Order
        public ActionResult Index(int? page)
        {
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = ToOrderConfigs.DefaultPageSize;

            int total;
            var orders = _orderService.GetAll(pageNumber, pageSize, out total);
            ViewBag.restaurant = _restaurantService.GetAll().ToList();

            return View(new StaticPagedList<Order>(orders, pageNumber, pageSize, total));
        }

        public ActionResult Search(int? restaurantId, decimal? amount, DateTime? fromDate, DateTime? toDate, int? page)
        {
            ViewBag.restaurant = _restaurantService.GetAll().ToList();
            ViewBag.restaurants = restaurantId;

            int pageNumber = page != null ? page.Value : 1;
            int pageSize = ToOrderConfigs.DefaultPageSize;

            int total;

            var orders = _orderService.GetAll(r => (restaurantId == null || r.RestaurantId == restaurantId) && (amount == null || r.NetAmount >= amount) && (fromDate == null || r.Date >= fromDate) && (toDate == null || r.Date <= toDate), pageNumber, pageSize, out total);
            return View("Index", new StaticPagedList<Order>(orders, pageNumber, pageSize, total));
        }
        public ActionResult OrdersToday(int? page)
        {
            DateTime NewDateValue = System.DateTime.Now.Date;
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = 10;
            int total;
            var orders = _orderService.GetAll(c => c.Date.Date == NewDateValue, pageNumber, pageSize, out total);
            return View(new StaticPagedList<Order>(orders, pageNumber, pageSize, total));
        }
        public ActionResult SearchTodaysOrders(string order, int? page)
        {
            DateTime NewDateValue = System.DateTime.Now.Date;
            ViewBag.orders = order;
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = 10;

            int total;
            var orders = _orderService.GetAll(c =>  c.Date.Date == NewDateValue, pageNumber, pageSize, out total);
            return PartialView("OrdersToday", new StaticPagedList<Order>(orders, pageNumber, pageSize, total));
        }
        public ActionResult RestaurantsToday(int? page)
        {
            DateTime NewDateValue = System.DateTime.Now.Date;
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = 10;
            int total;
            var restaurants = _restaurantService.GetAll(c => c.CreationDate.Date == NewDateValue, pageNumber, pageSize, out total);
            return View(new StaticPagedList<Restaurant>(restaurants, pageNumber, pageSize, total));
        }
        public ActionResult SearchRestaurantTodays(string restaurant, int? page)
        {
            DateTime NewDateValue = System.DateTime.Now.Date;
            ViewBag.restaurant = restaurant;
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = 10;

            int total;
            var restaurants = _restaurantService.GetAll(c => c.CreationDate.Date == NewDateValue, pageNumber, pageSize, out total);
            return PartialView("RestaurantsToday", new StaticPagedList<Restaurant>(restaurants, pageNumber, pageSize, total));
        }
        public ActionResult OrderDetails(int orderId)
        {
            var orders = _orderService.GetById(orderId);

            return PartialView("OrderDetail", orders);
        }
        public ActionResult RestaurantDetails(int restaurantId)
        {
            var restaurant = _restaurantService.GetById(restaurantId);

            return PartialView("RestaurantDetail", restaurant);
        }
    }
}

ToOrder.Web/Areas/RestaurantAdmin/Controllers/OrderController.cs
using Newtonsoft.Json;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToOrder.Core.Entities;
using ToOrder.Core.Services.Interfaces;
using ToOrder.Web.App_Start;
using ToOrder.Web.Controllers;
using ToOrder.Localization;

namespace ToOrder.Web.Areas.RestaurantAdmin.Controllers
{
    [Authorize(Roles = "Admin,RestaurantOwner,RestaurantUser")]
    public class OrderController : BaseController
    {
        IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        // GET: RestaurantAdmin/Order
        public ActionResult Index(int? page)
        {

            var restaurantId = this.CurrentRestaurantId();
            if (restaurantId == 0)
                return RedirectToAction("MyRestaurants", "Restaurant");
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = ToOrderConfigs.DefaultPageSize;

            int total;
            ViewBag.Header = Resources.UnservedOrders;
            var orders = _orderService.GetAll(c => c.IsServed == false && c.RestaurantId == restaurantId, pageNumber, pageSize, out total);

            return View(new StaticPagedList<Order>(orders, pageNumber, pageSize, total));
        }
        public ActionResult Search(string order, int? page)
        {
            ViewBag.order = order;

            int pageNumber = page != null ? page.Value : 1;
            int pageSize = ToOrderConfigs.DefaultPageSize;
            var restaurantId = this.CurrentRestaurantId();
            int total;


            var orders = _orderService.GetAll(c => c.IsServed == false && c.RestaurantId == restaurantId, pageNumber, pageSize, out total);
            return View("Index", new StaticPagedList<Order>(orders, pageNumber, pageSize, total));
        }

        // GET: RestaurantAdmin/Order
        public ActionResult Served(int? page)
        {

            var restaurantId = this.CurrentRestaurantId();
            if (restaurantId == 0)
                return RedirectToAction("MyRestaurants", "Restaurant");
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = ToOrderConfigs.DefaultPageSize;
            int total;
            ViewBag.Header = Resources.PreviousOrders;
            var orders = _orderService.GetAll(c => c.IsServed && c.RestaurantId == restaurantId, pageNumber, pageSize, out total);

            return View("Index", new StaticPagedList<Order>(orders, pageNumber, pageSize, total));
        }

        // GET: RestaurantAdmin/Order/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RestaurantAdmin/Order/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RestaurantAdmin/Order/Create
        [HttpPost]
        public ActionResult Create(Order order)
        {
            return View();
        }

        // GET: RestaurantAdmin/Order/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RestaurantAdmin/Order/Edit/5
        [HttpPost]
        public ActionResult Edit(Order order)
        {
            return View();
        }

        // GET: RestaurantAdmin/Order/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RestaurantAdmin/Order/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            return View();
        }

        public JsonResult GetBarGraphData()
        {

            var restaurantId = this.CurrentRestaurantId();
            var orders = _orderService.GetAll(c => c.RestaurantId == restaurantId && (c.Date > DateTime.Now.AddDays(-7))).OrderBy(x => x.Date).GroupBy(item => item.Date.Date).OrderBy(g => g.Key).
                        Select(i => new Order { Date = i.Key.Date, GrossAmount = i.Sum(w => w.GrossAmount) }).ToList();
            var from = DateTime.Now.AddDays(-7);

            var to = DateTime.Now.AddDays(-1);

            var days = Enumerable.Range(0, 1 + to.Subtract(from).Days)
                  .Select(offset => from.AddDays(offset))
                  .ToArray();

            var data = days.Select(i => new Order { Date = i.Date, GrossAmount = orders.Where(p => p.Date == i.Date).Sum(w => w.GrossAmount) }).ToList();

            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetLineGraphData()
        {


            var restaurantId = this.CurrentRestaurantId();
            var orders = _orderService.GetAll(c => c.RestaurantId == restaurantId && (c.Date > DateTime.Now.AddDays(-30))).OrderBy(x => x.Date).GroupBy(item => item.Date.Date).OrderBy(g => g.Key).
                        Select(i => new Order { Date = i.Key.Date, GrossAmount = i.Sum(w => w.GrossAmount) }).ToList();
            var from = DateTime.Now.AddDays(-30);

            var to = DateTime.Now.AddDays(-1);

            var days = Enumerable.Range(0, 1 + to.Subtract(from).Days)
                  .Select(offset => from.AddDays(offset))
                  .ToArray();

            var data = days.Select(i => new Order { Date = i.Date, GrossAmount = orders.Where(p => p.Date == i.Date).Sum(w => w.GrossAmount) }).ToList();

            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult BarGraphOrder()
        {
            return View();
        }
        public ActionResult LineGraphOrder()
        {
            return View();
        }
        public ActionResult UnservedOrders(int? page)
        {
            var restaurantId = this.CurrentRestaurantId();
            if (restaurantId == 0)
                return RedirectToAction("MyRestaurants", "Restaurant");
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = 6;
            int total;
            var orders = _orderService.GetAll(c => c.IsServed == false && c.RestaurantId == restaurantId, pageNumber, pageSize, out total);
            //return View(orders);
            return View(new StaticPagedList<Order>(orders, pageNumber, pageSize, total));
        }
        public ActionResult SearchUnservedOrders(string order, int? page)
        {
            ViewBag.orders = order;
            var restaurantId = this.CurrentRestaurantId();
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = 6;

            int total;


            var orders = _orderService.GetAll(c => c.IsServed == false && c.RestaurantId == restaurantId, pageNumber, pageSize, out total);
            return PartialView("UnservedOrders", new StaticPagedList<Order>(orders, pageNumber, pageSize, total));
        }
        public ActionResult LatestOrders(int? page)
        {
            DateTime NewDateValue = System.DateTime.Now.AddDays(-2);
            var restaurantId = this.CurrentRestaurantId();
            if (restaurantId == 0)
                return RedirectToAction("MyRestaurants", "Restaurant");
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = 6;
            int total;
            var orders = _orderService.GetAll(c => c.RestaurantId == restaurantId && c.Date > NewDateValue, pageNumber, pageSize, out total).OrderByDescending(x => x.Date);
            // return View(orders);
            return View(new StaticPagedList<Order>(orders, pageNumber, pageSize, total));
        }
        public ActionResult SearchLatestOrders(string order, int? page)
        {
            DateTime NewDateValue = System.DateTime.Now.AddDays(-2);
            ViewBag.orders = order;
            var restaurantId = this.CurrentRestaurantId();
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = 6;

            int total;


            var orders = _orderService.GetAll(c => c.RestaurantId == restaurantId && c.Date > NewDateValue, pageNumber, pageSize, out total).OrderByDescending(x => x.Date);
            return PartialView("UnservedOrders", new StaticPagedList<Order>(orders, pageNumber, pageSize, total));
        }

        public ActionResult ShowBarGraphOrders(int? page)
        {
            var restaurantId = this.CurrentRestaurantId();
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = ToOrderConfigs.DefaultPageSize;

            int total;
            var orders = _orderService.GetAll(c => c.RestaurantId == restaurantId && (c.Date > DateTime.Now.AddDays(-7)), pageNumber, pageSize, out total);
            ViewBag.Header = "Last Seven Days Orders";
            return View("Index", new StaticPagedList<Order>(orders, pageNumber, pageSize, total));
        }
        public ActionResult ShowLineGraphOrders(int? page)
        {
            var restaurantId = this.CurrentRestaurantId();
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = ToOrderConfigs.DefaultPageSize;

            int total;
            var orders = _orderService.GetAll(c => c.RestaurantId == restaurantId && (c.Date > DateTime.Now.AddDays(-30)), pageNumber, pageSize, out total);
            ViewBag.Header = "Last 30 Days  Orders";
            return View("Index", new StaticPagedList<Order>(orders, pageNumber, pageSize, total));
        }
        public ActionResult UnservedOrderDetails(int Id, int? page)
        {
            var restaurantId = this.CurrentRestaurantId();
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = ToOrderConfigs.DefaultPageSize;

            int total;
            var orders = _orderService.GetAll(c => c.RestaurantId == restaurantId && (c.Id == Id), pageNumber, pageSize, out total);
            ViewBag.Header = "Unserved Order";
            return View("Index", new StaticPagedList<Order>(orders, pageNumber, pageSize, total));
        }

ToOrder.Web/Controllers/OrderController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToOrder.Core.Entities;
using ToOrder.Core.Services.Interfaces;
using ToOrder.Web.App_Start;

namespace ToOrder.Web.Controllers
{
    public class OrderController : BaseController
    {
        IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        // GET: User/Order
        public ActionResult Index(int? page)
        {
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = ToOrderConfigs.DefaultPageSize;
            int total;

            var authenticatedUser = GetAuthenticatedUser();

            var orders = _orderService.GetAll(O => O.UserId == authenticatedUser.Id, pageNumber, pageSize, out total).OrderByDescending(O => O.Date);

            return PartialView(new StaticPagedList<Order>(orders, pageNumber, pageSize, total));
        }

        // GET:User/Order/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult UserRecentRestaurants()
        {
            var authenticatedUser = GetAuthenticatedUser();

            var restaurants = _orderService.GetAll(O => O.UserId == authenticatedUser.Id).OrderByDescending(O => O.Date).Select(i => i.Restaurant).Distinct().Take(4);

            return PartialView("RecentRestaurants", restaurants);
        }


    }
}

ToOrder.Web/Controllers/OrderDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToOrder.Core.Entities;
using ToOrder.Core.Services.Interfaces;
using ToOrder.Web.App_Start;


namespace ToOrder.Web.Controllers
{
    public class OrderDetailsController : BaseController
    {
        IOrderDetailService _orderDetailService;

        public OrderDetailsController(IOrderDetailService orderDetailService)
        {
            _orderDetailService = orderDetailService;
        }

        // GET: OrderDetails
        public ActionResult Index(int orderId)
        {
            var orderDetails = _orderDetailService.GetAll(o => o.OrderId == orderId);

            return PartialView(orderDetails.ToList());
        }

        // GET: OrderDetail/Details/5
        public ActionResult Details(int orderId)
        {
            return View();
        }

        // GET: OrderDetail/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OrderDetail/Create
        [HttpPost]
        public ActionResult Create(OrderDetails orderDetails)
        {
            return View();
        }

        // GET: OrderDetail/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: OrderDetail/Edit/5
        [HttpPost]
        public ActionResult Edit(OrderDetails orderDetails)
        {
            return View();
        }

        // GET: OrderDetail/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: OrderDetail/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            return View();
        }
    }
}

ToOrder.Web/Areas/Admin/Views/Order/GoogleMapPartial.cshtml
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="section-title">
            <span class="glyphicon glyphicon-globe"></span>  <label>Location Map</label>
        </div>
        <div id="map" style="width:100%;height:300px;"></div>
    </div>
}

<script>
    var myCenter;
    var mapOptions;
    var map;
    var marker;
    var infowindow;
    function myMap() {

        var geocoder = new google.maps.Geocoder();
        var address = document.getElementById('Address_Locality').value;
        var lat = document.getElementById('Latitude').value;
        var lon = document.getElementById('Longitude').value;
        var zoomVal = parseInt(document.getElementById('Zoom').value);
        if (zoomVal == 0) {
            zoomVal = 13;
        }

        if (lat == 0 || lon == 0) {
            geocoder.geocode({ 'address': address }, function (results, status) {
                if (status == 'OK') {
                    myCenter = new google.maps.LatLng(results[0].geometry.location.lat(), results[0].geometry.location.lng());
                    mapOptions = { center: myCenter, zoom: zoomVal }

                    document.getElementById('Latitude').value = results[0].geometry.location.lat();
                    document.getElementById('Longitude').value = results[0].geometry.location.lng();

                    MapInfo();
                }
                else {
                    alert('Geocode was not successful for the following reason: ' + status);
                }
            });
        }
        else {
            myCenter = new google.maps.LatLng(lat, lon);
            mapOptions = { center: myCenter, zoom: zoomVal };

            MapInfo();
        }
    }

    function MapInfo() {
        var mapCanvas = document.getElementById("map");
        map = new google.maps.Map(mapCanvas, mapOptions);
        marker = new google.maps.Marker({ position: myCenter, draggable: false });
        marker.setMap(map);

        infowindow = new google.maps.InfoWindow({
            content: "<b>Latitude:  </b>" + myCenter.lat() + "<br/> <b>Longitude:  </b>" + myCenter.lng() + "<br/><br/><i>Drag to change</i>"
        });
        infowindow.open(map, marker);
    }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDZkNTEJ2QUqe6PyeOVOBwjUuKzg7YeE2A&callback=myMap"></script>

ToOrder.Web/Areas/Admin/Views/Order/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<ToOrder.Core.Entities.Order>

@{
    ViewBag.Title = "Index";
}

@section Scripts{
    <script>
        $(function () {

            $(".tablesorter").tablesorter({
                sortReset: true,
                sortRestart: true,
                sortInitialOrder: 'desc',
                headers: { 6: { sorter: false } }

            });
        });

        $(function () {
            $('#fromDate').datepicker({
                dateFormat: "dd-M-y",
                changeMonth: true,
                changeYear: true,
            });
        })
        $(function () {
            $('#toDate').datepicker({
                dateFormat: "dd-M-y",
                changeMonth: true,
                changeYear: true,
            });
        })
    </script>

}


@section pageHeader{
    <h5>@Resources.Orders</h5>
}

<div class="row section">

    <div class="col-md-6">
        @using (Html.BeginForm("Search", "Order", FormMethod.Get, new { @class = "form-horizontal" }))
        {
            <div class="form-group">
                @Html.Label(Resources.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-9">
                    @Html.DropDownList("restaurantId", new SelectList(ViewBag.restaurant, "Id", "Name"), "", new { @class = "form-control" })
                    @Html.ValidationMessage("restaurant")
                </div>
            </div>
            <div class="form-group">
                <label for="@Resources.Amount" class="col-md-3 control-label">@Resources.Amount</label>
                <div class="col-md-9">
                    <input type="text" name="amount" class="form-control" id="amount" placeholder="">
                </div>
            </div>
            <div class="form-group">
                <label for="@Resources.FromDate" class="col-md-3 control-label">@Resources.FromDate</label>
                <div class="col-md-4">
                    <input type="text" name="fromDate" class="form-control" id="fromDate" placeholder="">
                </div>
                <label for="@Resources.ToDate" class="col-md-1 control-label">@Resources.ToDate</label>
                <div class="col-md-4">
                    <input type="text" name="toDate" class="form-control" id="toDate" placeholder="">
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-3 col-md-9">
                    <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i> @Resources.Search</button>
                </div>
            </div>
        }
    </div>

</div>

<div class="section">

    <div>
        <table class="table table-hover table-responsive  tablesorter">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayName(Resources.Date)
                    </th>
                    <th>
                        @Html.DisplayName("Restaurant")
                    </th>
                    <th>
                        @Resources.User @Resources.Name
                    </th>
                    <th>
                        @Html.DisplayName(Resources.GrossAmount)
                    </th>
                    <th>
                        @Html.DisplayName(Resources.Tax)
                    </th>
                    <th>
                        @Html.DisplayName(Resources.NetAmount)
                    </th>
                    <th></th>
                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Restaurant.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GrossAmount)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.Tax)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NetAmount)
                    </td>
                    <td>
                        @Ajax.ActionLink(Resources.Delete, "Delete", new { id = item.Id }, new AjaxOptions { UpdateTargetId = "ajaxDialog", InsertionMode = InsertionMode.Replace, HttpMethod = "Get", OnSuccess = "showDialog" }, new { @class = "btn btn-default btn-xs" })
                    </td>
                </tr>
            }

        </table>

    </div>

    <div class="text-right ">
        @Html.PagedListPager(Model, page => Url.Action("Search", new { page, restaurantId = ViewBag.restaurants }))
    </div>

</div>

ToOrder.Web/Areas/Admin/Views/Order/OrderDetail.cshtml
@model ToOrder.Core.Entities.Order

<div class="container" style="background-color:white;">
@using (Ajax.BeginForm(new AjaxOptions { OnSuccess = "handleSuccessOrders", OnFailure = "handleError" }))
    {
    @Html.AntiForgeryToken()
    <h4>@Resources.Orders# @Html.DisplayFor(model => model.Id)</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)


    <div class="form-horizontal">

        <div class="form-group">
            <div class="col-md-9 col-md-offset-2">

                <div class="col-md-offset-2">
                    <label class="control-label" for="@Resources.Name">Restaurant @Resources.Name:</label>  <span>@Html.ValueFor(model => model.Restaurant.Name) </span><br />
                    <label class="control-label" for="@Resources.Date">@Resources.Date:</label>  <span>@Html.ValueFor(model => model.Date) </span><br />
                    <label class="control-label" for="@Resources.GrossAmount">@Resources.GrossAmount:</label>  <span>@Html.ValueFor(model => model.GrossAmount) </span><br />

                    <label class="control-label" for="@Resources.Tax">@Resources.Tax:</label>  <span>@Html.ValueFor(model => model.Tax) </span><br />
                    <label class="control-label" for="@Resources.NetAmount">@Resources.NetAmount:</label>  <span>@Html.ValueFor(model => model.NetAmount) </span><br />
                </div>
                <hr />
            </div>

        </div>

    </div>
}
</div>

ToOrder.Web/Areas/Admin/Views/Order/OrdersToday.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<ToOrder.Core.Entities.Order>
@{
    Layout = null;
}



<div id="replaceDiv" style="background-color:white">
    <h4 class="text-uppercase" style="color:rgba(118, 118, 118, 1.0);">@Resources.TodaysOrders</h4>
    <div style="height:420px">
        <table class="table table-hover table-responsive  tablesorter" id="TodayTable">

            <tr>
                <th>
                    @Html.DisplayName(@Resources.OrderId)
                </th>
                <th>
                    @Html.DisplayName(@Resources.RestaurantName)
                </th>
                <th>
                    @Html.DisplayName(@Resources.CustomerName)
                </th>
                <th>
                    @Html.DisplayName(@Resources.TotalOrderAmount)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Ajax.ActionLink(item.Id.ToString(), "OrderDetails", "Order", new { area = "admin", orderId = item.Id }, new AjaxOptions { UpdateTargetId = "ajaxDialog", InsertionMode = InsertionMode.Replace, HttpMethod = "Get", OnSuccess = "showDialog"})
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Restaurant.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.User.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.GrossAmount)
                    </td>
                </tr>
            }

        </table>
    </div>
    <div class="text-right ">
        @Html.PagedListPager(Model, page => Url.Action("SearchTodaysOrders", new { page, order = ViewBag.order }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions { HttpMethod = "get", InsertionMode = InsertionMode.Replace, UpdateTargetId = "replaceDiv" }))
    </div>
</div>

ToOrder.Web/Areas/Admin/Views/Order/RestaurantsToday.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<ToOrder.Core.Entities.Restaurant>
@{
    Layout = null;
}

<div id="replaceDiv2" style="background-color:white">
    <h4 class="text-uppercase" style="color:rgba(118, 118, 118, 1.0);">@Resources.RestaurantsAddedToday</h4>
    <div style="height:420px">
        <table class="table table-hover table-responsive  tablesorter" id="TodayTable">

            <tr>
                <th>
                    @Html.DisplayName(@Resources.RestaurantName)
                </th>
                <th>
                    @Html.DisplayName(@Resources.Locality)
                </th>
                <th>
                    @Html.DisplayName(@Resources.Contact)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Ajax.ActionLink(item.Name.ToString(), "RestaurantDetails", "Order", new { area = "admin", restaurantId = item.Id }, new AjaxOptions { UpdateTargetId = "ajaxDialog", InsertionMode = InsertionMode.Replace, HttpMethod = "Get", OnSuccess = "showDialog" })
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Address.Region)
                    </td>
                    <td>
                        @Html.DisplayFor(model => item.Contact.Telephone)
                    </td>
                </tr>
            }

        </table>
    </div>
    <div class="text-right ">
        @Html.PagedListPager(Model, page => Url.Action("SearchRestaurantTodays", new { page, restaurant = ViewBag.restaurant }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions { HttpMethod = "get", InsertionMode = InsertionMode.Replace, UpdateTargetId = "replaceDiv2" }))
    </div>
</div>