ToOrder.Web/Controllers/BannerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToOrder.Core.Entities;
using ToOrder.Web.App_Start;
using ToOrder.Core.Services.Interfaces;
using ToOrder.Data;

namespace ToOrder.Web.Controllers
{
    public class BannerController : BaseController
    {
        IBannerService _bannerService;


        public BannerController(IBannerService bannerService)
        {
            _bannerService = bannerService;
        }

        // GET: Banner
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ShowCarousel()
        {
            var banners = _bannerService.GetAll(b => b.IsActive && (b.FromDate <= DateTime.Now.Date && b.ToDate >= DateTime.Now.Date)).Take(4);

            return PartialView(banners);
        }
    }
}

ToOrder.Web/Controllers/CuisineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToOrder.Core.Services.Interfaces;

namespace ToOrder.Web.Controllers
{

    public class CuisineController : Controller
    {
        ICuisineService _cuisineService;
        IRestaurantCuisineService _restaurantCuisineService;

        public CuisineController(ICuisineService cuisineService, IRestaurantCuisineService restaurantCuisineService)
        {
            _cuisineService = cuisineService;
            _restaurantCuisineService = restaurantCuisineService;
        }

        // GET: Cuisine
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult SearchByCuisine()
        {
            var cuisines = _cuisineService.GetAll().OrderBy(c => c.Name);
            return PartialView(cuisines);
        }

        public ActionResult ShowCuisines(int restaurantId)
        {
            var cuisines = _restaurantCuisineService.GetAll(c => c.RestaurantId == restaurantId);
            return PartialView("ShowCuisinesPartial", cuisines);
        }
    }
}

ToOrder.Web/Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToOrder.Core.Entities;
using ToOrder.Web.Helpers;

namespace ToOrder.Web.Controllers
{
    public class LanguageController : BaseController
    {
       
        // [ChildActionOnly]
        public ActionResult LanguageSelector()
        {

            Language language = new Language();
            language.Culture = cultureName;
            return PartialView("LanguageSelector", language);
        }


        public ActionResult SetCulture(string culture)
        {
            // Validate input
            culture = CultureHelper.GetImplementedCulture(culture);  //todo: pass supported cultures from Language

            // Save culture in a cookie
            HttpCookie cookie = Request.Cookies["_culture"];
            if (cookie != null)
                cookie.Value = culture;   // update cookie value
            else
            {
                cookie = new HttpCookie("_culture");
                cookie.Value = culture;
                cookie.Expires = DateTime.Now.AddYears(1);
            }

            Response.Cookies.Add(cookie);
            return Redirect(Request.UrlReferrer.ToString());
        }
    }
}

ToOrder.Web/Controllers/OrderController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToOrder.Core.Entities;
using ToOrder.Core.Services.Interfaces;
using ToOrder.Web.App_Start;

namespace ToOrder.Web.Controllers
{
    public class OrderController : BaseController
    {
        IOrderService _orderService;

        public OrderController(IOrderService orderService)
        {
            _orderService = orderService;
        }

        // GET: User/Order
        public ActionResult Index(int? page)
        {
            int pageNumber = page != null ? page.Value : 1;
            int pageSize = ToOrderConfigs.DefaultPageSize;
            int total;

            var authenticatedUser = GetAuthenticatedUser();

            var orders = _orderService.GetAll(O => O.UserId == authenticatedUser.Id, pageNumber, pageSize, out total).OrderByDescending(O => O.Date);

            return PartialView(new StaticPagedList<Order>(orders, pageNumber, pageSize, total));
        }

        // GET:User/Order/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult UserRecentRestaurants()
        {
            var authenticatedUser = GetAuthenticatedUser();

            var restaurants = _orderService.GetAll(O => O.UserId == authenticatedUser.Id).OrderByDescending(O => O.Date).Select(i => i.Restaurant).Distinct().Take(4);

            return PartialView("RecentRestaurants", restaurants);
        }


    }
}

ToOrder.Web/Areas/Admin/Views/Shared/_BackofficeLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/AdminSite.css" rel="stylesheet">
    @Scripts.Render("~/bundles/jquery")
    <script type="text/javascript" src="~/Scripts/adminscript.js"></script>
</head>
<body>

    <nav class="navbar navbar-default navbar-fixed-top">

        @if (IsSectionDefined("header"))
        {
        @RenderSection("header")
        }
        else
        {
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand  " href="@Url.Action("Index","Home",new{area=""})"> <span class="logo"><b>2</b>ordr</span></a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">

                    <li>

                        <a href="@Url.Action("Index","Home",new{area=""})" class=""><i class="glyphicon glyphicon-home"></i> Website</a>

                    </li>

                    <li>
                        <span class="glyphicon glyphicon-globe" style="color:#777;"></span>@{Html.RenderAction("LanguageSelector", "Language", new { area = "" });}
                    </li>


                    <li>

                        <a href="@Url.Action("SignOut","Account",new{area=""})" class=""><i class="glyphicon glyphicon-user"></i> Sign Out</a>

                    </li>
                </ul>
            </div>
        </div>
        }
    </nav>

    <div class="fixed-sidebar-left">
        <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 100%;">
            <ul class="nav navbar-nav side-nav nicescroll-bar" style="overflow: hidden; width: auto; height: 100%;">
                <li><a id="restDashboard" href="@Url.Action("Dashboard", "Restaurant", new { area = "admin" })"><i class=" glyphicon glyphicon-picture"></i> Dashboard</a></li>
                <li><a id="restIndex" href="@Url.Action("Index", "Restaurant", new { area = "admin" })"><i class="glyphicon glyphicon-glass"></i> Restaurant</a></li>
                <li><a id="cuisine" href="@Url.Action("Index", "Cuisine", new { area = "admin" })"><i class="glyphicon glyphicon-home"></i> Cuisine</a></li>
                <li><a id="rating" href="@Url.Action("Index", "Rating", new { area = "admin" })"><i class="glyphicon glyphicon-home"></i> Rating</a></li>
                <li><a id="order" href="@Url.Action("Index", "Order", new { area = "admin" })"><i class="glyphicon glyphicon-list-alt"></i> Order</a></li>
                <li><a id="banner" href="@Url.Action("Index", "Banner", new { area = "admin" })"><i class="glyphicon glyphicon-list-alt"></i> @Resources.Banners</a></li>

            </ul>
        </div>
    </div>

    <div class="page-wrapper" style="min-height:900px;">
        <div class="container-fluid">
            <div class="row heading-bg bg-yellow txt-light">
                @RenderSection("pageHeader", false)
            </div>

            <div class="row">
                @RenderBody()
            </div>
        </div>

    </div>
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryUI")
    @Scripts.Render("~/bundles/jqueryAjax")
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript" src="~/Scripts/tablesorter/jquery.metadata.js"></script>
    <script type="text/javascript" src="~/Scripts/tablesorter/jquery.tablesorter.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>